services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - airflow
  
  email_sender:
    image: email_sender:latest
    ports:
      - "5000:5000"
    env_file:
      - ./include/modules/email_sender/.env
    networks:
      - airflow
 