services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - airflow
  
  email-sender:
    build:
      context: ./email_sender
      dockerfile: Dockerfile
    image: email-sender:latest  # <-- ensures consistent tagging
    ports:
      - "5001:5000"
    env_file:
      - ./email-sender/.env
